name: CI

on:
  push:
    branches: ["main"]        # 👈 merge vào main → chạy CI
  pull_request:
    branches: ["main"]        # 👈 tạo PR vào main → chạy CI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npm test