name: CI

on:
  push:
    branches: ["main", "master"]   # chạy khi merge vào main/master
  pull_request:
    branches: ["main", "master"]   # chạy khi tạo PR vào main/master

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test